/** Long professional template prompts (≥800 chars). LRM-906 / T1. */
export const RESEARCH_TEMPLATE_PROMPTS = {
  industry: {
    zh: [
      "请围绕用户指定的目标行业完成一轮可交付、可复查的结构化调研，并把事实、估算、判断和建议明确分开。",
      "先定义市场边界与统计口径，包括地域、时间范围、客户类型、产品形态、收入是否含税以及产业链层级；存在多种通行口径时并列展示，禁止把不同口径的数据直接相加。",
      "将用户目标拆成必须回答的问题、可选探索问题和当前未知项，说明每个问题对最终决策的影响，并在调研过程中根据新证据调整优先级。",
      "市场规模至少采用两种独立方法交叉估算，例如自上而下的权威统计与自下而上的客户数乘客单价，并展示公式、单位、基准年份、关键假设和敏感性区间。",
      "增长分析覆盖近三至五年的历史变化与未来驱动，区分名义增长、实际增长、一次性冲击和结构性趋势，不得用单个预测机构的远期数字代替推导。",
      "产业链部分绘制上游供给、中游产品或服务、下游渠道与终端需求之间的价值流，指出议价权、利润池、转换成本和可能被替代的环节。",
      "玩家研究应覆盖头部、腰部、新进入者及跨界替代者，逐项比较定位、客户、产品组合、定价、渠道、商业模式、资本与组织能力以及可验证的护城河。",
      "竞争结论不能只复述公司宣传材料；官网与公告用于确认事实，客户案例、监管材料、财报、招投标、招聘和可信行业数据用于交叉验证实际经营信号。",
      "政策与合规部分列出适用地区的监管主体、已生效规则、已公布但未生效规则及执行案例，说明政策影响对象、触发条件和最可能的业务后果。",
      "技术变量需要说明成熟度、成本曲线、部署限制、关键依赖和替代路径，避免把实验室能力、供应商演示或媒体热度直接等同于规模化可用。",
      "需求侧研究区分购买者、使用者和受益者，说明采购流程、预算来源、决策周期、留存因素与不采用的原因；缺少直接调研时标注推断边界。",
      "对近十二至二十四个月的重要事件建立时间线，标明事件日期、证据发布日期以及它改变了哪项假设，避免用过期资料描述当前市场。",
      "每个主要结论至少连接一条可定位来源；高影响结论优先要求两个独立来源，镜像转载、同集团材料和互相引用的报告不得计为独立支持。",
      "来源按一手数据、权威二手材料、行业访谈或案例、一般媒体与弱信号分级，记录发布日期、访问日期、适用范围、潜在利益关系和可信度。",
      "当来源相互冲突时保留各自口径与原始数字，分析差异来自样本、定义、时间还是利益立场，再给出当前更可信的判断及改变判断所需的新证据。",
      "机会评估写清目标客户、未满足需求、为什么现在出现窗口、进入条件、可获得优势和首个验证动作，并给出成功信号、失败信号及验证成本。",
      "风险清单按发生概率与影响程度排序，覆盖市场、竞争、供应、技术、政策、财务和执行风险，每项都写触发条件、先行指标和可采取的处理方式。",
      "最终交付包含执行摘要、范围与方法、市场规模推导、产业链地图、竞争格局表、需求与趋势、政策技术变量、机会排序、风险与未知项以及下一步验证计划。",
      "执行摘要只保留能改变决策的发现，并区分已证实结论、有条件判断和待验证假设；正文中的数字、表格和建议必须能够回溯到证据或计算过程。",
      "用户给出的品类、地区、预算、时间或能力约束高于通用框架；若约束之间冲突，应展示取舍并给出条件化建议，不得悄悄删除不利条件。",
      "信息不足时先列缺口、已尝试的检索方向和暂时无法确认的原因，再提供带条件与置信度的结论；不得为了完整外观制造数据、来源或确定性。",
      "语言保持具体克制，中英专名首次出现可括注，表格字段保持统一单位与统计期，任何建议都要说明依据、适用条件和下一步动作。",
    ].join(""),
    en: "Conduct a structured, delivery-ready industry study for the user-specified sector. Define market boundaries and measurement scope (geography, segments, product forms), estimate market size and 3–5 year growth with methods and assumptions, map the value chain and major players/business models, and contrast leaders vs mid-tier on positioning, pricing, channels, and moats. Summarize key trends, policy/tech shifts, and unresolved uncertainties over the last 12–24 months. Deliver an executive summary, market map, competitive landscape table, opportunity/risk list, and next validation questions. When the user adds category/region/budget constraints, those override the generic frame. Prefer primary and authoritative secondary sources; cite provenance and credibility; present conflicting views with a reasoned lean. Avoid buzzword lists—every claim needs checkable evidence. Default focus: market size, competitive landscape, growth drivers, risks & unknowns. Stay professional; if information is thin, list gaps before conditional conclusions. Expand with concrete examples tied to the user's industry whenever provided.",
  },
  competitor: {
    zh: [
      "请针对用户指定的品类完成可用于产品、定价和进入策略决策的竞品调研，并明确直接竞品、间接替代、潜在跨界者与不纳入对象的边界。",
      "先还原用户自身的目标客户、使用场景、价值主张、资源约束和成功标准；这些信息缺失时列为待确认项，并避免假设所有产品服务同一类客户。",
      "建立候选池后使用一致的筛选规则形成通常四至八家的短名单，说明入选理由、排除理由以及可能遗漏的区域性或垂直领域玩家。",
      "每家竞品记录公司与产品实体、适用市场、目标客群、核心场景、交付方式和资料更新时间，防止把同一公司的不同版本或已停止产品混为一体。",
      "功能比较围绕用户任务而不是菜单数量展开，区分已正式提供、受套餐限制、需要定制、公开测试和仅在路线图中的能力，并附可核验入口。",
      "定价研究拆解计费单位、套餐门槛、用量阶梯、席位限制、合同周期、实施与迁移费用、免费额度和潜在超额成本，必要时构造统一使用情景计算总拥有成本。",
      "获客与渠道分析覆盖自助购买、销售驱动、合作伙伴、应用市场、内容、社区和生态捆绑，使用流量、招聘、案例、活动或渠道政策等信号判断重点，而非复述品牌口号。",
      "客户与口碑证据应区分目标客群和使用版本，汇总高频优点、投诉、流失诱因与支持体验；评价平台样本偏差、激励评论和过期资料必须显式标注。",
      "商业模式部分比较收入来源、成本结构、扩张路径、交叉销售和服务依赖，财务数据不可得时使用可验证代理指标并说明代理指标不能证明什么。",
      "技术与运营能力比较部署模型、集成边界、数据迁移、性能、安全合规、可观测性、服务等级和客户支持，避免把一项基准测试外推到所有工作负载。",
      "品牌与组织研究关注可信度、垂直专业性、团队能力、资本状态、地区覆盖和合作网络，并把已验证事实与基于招聘或公开活动的推断分开。",
      "差异矩阵必须使用相同定义和时间点；无法确认的单元格写未知及验证办法，不允许用空白、主观等级或未经说明的加权总分掩盖证据差异。",
      "对每个主要差异解释它对哪类客户有价值、价值发生在购买还是使用阶段、竞品为何形成该差异以及用户是否有现实能力复制或绕开。",
      "机会假设采用目标人群、未满足任务、现有替代、差异化方案、为什么现在和可证伪实验的结构，给出成功阈值、最短验证周期与停止条件。",
      "红海判断需要证据支持，例如价格持续下探、功能快速同质化、获客成本上升或渠道被锁定；不得仅因竞品数量多就宣判不可进入。",
      "风险覆盖竞品快速跟进、平台依赖、专利或合规、数据可得性、迁移阻力、品牌信任和服务成本，并说明何种观察会提高或降低风险评级。",
      "来源优先使用产品文档、价格页、合同条款、状态页、合规证明、发布记录、财报和可定位客户案例，再用可信评测与社区材料补充实际体验。",
      "关键事实记录发布日期和访问日期；遇到地区差异、灰度发布、定制报价或页面动态变化时保存适用条件，不把旧截图当成当前全球能力。",
      "最终交付包含范围与方法、竞品短名单、客群与定位图、能力矩阵、标准化价格情景、渠道与口碑证据、逐家优劣势、机会优先级、风险和不做清单。",
      "结论按 P0 与 P1 排序，每项建议说明依据、预期影响、所需资源、验证动作和反证条件；不能从功能清单直接跳到战略推荐。",
      "当公开信息不足或来源冲突时保留未知项与不同说法，给出当前倾向及其置信度，并列出最值得进行的客户访谈、试用、报价或技术验证。",
      "用户补充的自身定位、预算、地区、团队能力或时间窗口应贯穿全部比较；语言保持具体克制，中英专名首次出现可括注。",
    ].join(""),
    en: "Run a competitor analysis for the user-specified category and produce actionable comparisons. Clarify scope (direct/indirect/adjacent) and evaluation dimensions, list major rivals (typically 4–8; explain if fewer), and compare capabilities, pricing/packaging, GTM/channels, brand sentiment, and typical buyers. Call out differentiation opportunities, what to chase first, and what to avoid. Deliver a shortlist, comparison matrix, strengths/weaknesses, opportunity hypotheses, and validation experiments. Cite public, verifiable signals with dates and source weight. If the user states our positioning or constraints, recommendations must map back to them. Do not dump feature lists—each opportunity must state for whom, why now, and how to test. Default dimensions: features, pricing, GTM, sentiment. Prioritize P0/P1 and include an explicit not-to-do list. Keep the tone crisp and decision-oriented for product and GTM owners.",
  },
  tech_selection: {
    zh: [
      "请围绕用户的实际业务目标完成技术选型调研，交付可以验证、实施和回退的推荐，并把硬约束、偏好、假设及未知项分别记录。",
      "先定义问题陈述、目标用户、预期负载、成功指标、上线窗口、预算、合规边界、数据敏感度、团队现状和不可接受的失败模式；缺失信息不得被默认成有利条件。",
      "把需求拆为必须满足、应当满足和可延后能力，为每项给出可测验收标准，避免使用性能好、生态成熟、容易维护等没有量化口径的描述。",
      "候选方案同时包含主流路径、约束下可能更合适的替代路径和维持现状方案，说明初筛规则及淘汰原因，防止只研究预先偏好的工具。",
      "能力边界按真实用户流程核对，包括开发、测试、部署、运行、内容生产、数据管理、权限、安全、可观测性、故障处理和退出迁移，而非只比较产品功能表。",
      "性能研究明确工作负载、数据规模、并发、延迟分位数、吞吐、资源规格和测试版本；供应商基准、社区测试与自建实验分别标注，禁止跨场景直接比较数字。",
      "成本模型至少覆盖开发与学习、基础设施、调用或许可证、第三方服务、内容资产、测试、监控、支持、合规、迁移和失败返工，并给出低中高使用情景。",
      "生态成熟度通过版本历史、维护者与资金、发布频率、问题处理、文档、插件质量、人才与服务供给、生产案例和依赖健康度判断，不用下载量或明星数单独下结论。",
      "安全与合规检查数据流向、身份权限、密钥、供应链、内容版权、隐私、地区要求、审计、备份和事件响应，说明哪些责任由供应商承担、哪些仍属于使用方。",
      "集成与运维比较本地开发、持续集成、环境隔离、发布、回滚、监控、扩缩容、故障诊断、备份恢复和供应商支持，计算无人值守假设下仍需人工决策的环节。",
      "锁定风险拆成数据格式、运行时、专有接口、托管服务、商业条款和团队知识，针对每类写出可移植资产、替代品、退出步骤、时间成本和触发迁移的信号。",
      "若方案依赖人工智能生成代码或内容，应验证模型能力边界、上下文与工具接入、可重复测试、错误发现、版权来源、成本上限和人工缺席时的审批责任。",
      "涉及从零构建产品时，应把工作分解为需求与规则、原型、资产、前后端、数据、支付或账号、安全、质量保证、发布、运营和持续维护，逐段判断能否自动化。",
      "对无法仅凭文档确认的高风险能力设计最小可证伪实验，写明输入、环境、指标、通过阈值、失败阈值、预计成本和结果如何改变选型。",
      "架构建议展示系统边界、主要组件、数据与控制流、外部依赖和故障域，并说明每个组件为什么存在；不得通过增加中间层来掩盖候选方案本身不满足需求。",
      "推荐应给出首选、备选和不选方案，逐项回扣验收标准与约束，明确哪些差异有直接证据、哪些来自推断，以及选择在什么条件下会改变。",
      "实施路径从可工作的纵向样例开始，但覆盖到生产所需的测试、安全、监控、备份、发布和维护，不得把概念验证的成功描述成完整产品已经可交付。",
      "里程碑按可验证产物和退出条件组织，列出依赖顺序、并行工作、决策点、风险最高的先验验证及每阶段可以回滚到的状态，而非只给日期清单。",
      "风险表按触发条件、发生概率、影响、发现方式和处理动作描述，至少覆盖能力不足、成本失控、供应商变化、质量债务、安全合规与长期无人维护。",
      "证据优先来自官方文档、版本与价格记录、标准、公开基准、生产事故复盘和可核验案例；每条时效敏感信息标注版本、发布日期与访问日期。",
      "来源冲突时检查版本、配置、样本和利益关系，保留不同结果并给出适用范围；信息不足时明确缺口和下一项实验，不制造确定答案。",
      "最终交付包含约束与验收表、候选短名单、能力和风险矩阵、性能与成本模型、生态和锁定分析、实验计划、推荐架构、实施步骤、回滚方案及明确的能否做结论。",
      "结论使用具体条件和动作，中英专名首次出现可括注；用户新增的业务场景或限制覆盖通用模板，并贯穿计算、实验和推荐。",
    ].join(""),
    en: "Run a tech-selection study with an actionable recommendation. Clarify the problem, success criteria, hard constraints (performance, cost, compliance, skills, launch window) and candidate options. Compare options on capability fit, cost/performance, ecosystem maturity, ops complexity, and migration/lock-in risk; recommend a path, fallback, and migration notes. Deliver a constraints table, comparison table, recommendation with rationale, risks/rollback, and a 90-day milestone sketch. Evidence from official docs, benchmarks, production cases, and community health—cite versions/dates. If constraints conflict, expose trade-offs before a conditional pick; do not pretend a perfect option exists. Default focus: capability, cost & performance, ecosystem, migration risk. When the user supplies a business scenario, thread it through examples. Prefer concrete next actions over vague hedging.",
  },
} as const;
