/** Long professional template prompts (≥800 chars). LRM-906 / T1. */
export const RESEARCH_TEMPLATE_PROMPTS = {
  "industry": {
    zh: "请围绕用户指定的目标行业做一轮可交付的结构化调研。先界定市场边界与统计口径（地域、客群、产品形态），再估算市场规模与近 3–5 年增速，并说明估算方法与主要假设。梳理产业链上下游、主要玩家与商业模式，对比头部与腰部差异（定位、定价、渠道、护城河）。总结近 12–24 个月关键趋势、政策与技术变量，以及尚未验证的不确定因素。输出需包含：执行摘要、市场地图、竞争格局表、机会与风险清单、建议下一步验证问题。若用户补充了具体品类/地区/预算约束，以其为准覆盖通用框架。证据优先一手与权威二手来源，标注出处与可信度，冲突观点并列呈现并给倾向判断。不要空泛罗列名词；每条结论对应可复查依据。关注维度默认覆盖市场规模、竞争格局、增长驱动、风险与不确定因素，用户另有指定时以用户为准。交付语气专业克制，避免营销腔。若信息不足，先列出缺口再给有条件结论。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。",
    en: "Conduct a structured, delivery-ready industry study for the user-specified sector. Define market boundaries and measurement scope (geography, segments, product forms), estimate market size and 3–5 year growth with methods and assumptions, map the value chain and major players/business models, and contrast leaders vs mid-tier on positioning, pricing, channels, and moats. Summarize key trends, policy/tech shifts, and unresolved uncertainties over the last 12–24 months. Deliver an executive summary, market map, competitive landscape table, opportunity/risk list, and next validation questions. When the user adds category/region/budget constraints, those override the generic frame. Prefer primary and authoritative secondary sources; cite provenance and credibility; present conflicting views with a reasoned lean. Avoid buzzword lists—every claim needs checkable evidence. Default focus: market size, competitive landscape, growth drivers, risks & unknowns. Stay professional; if information is thin, list gaps before conditional conclusions. Expand with concrete examples tied to the user's industry whenever provided.",
  },
  "competitor": {
    zh: "请对用户指定品类做竞品分析并形成可执行对比结论。先明确对比范围（直接竞品/间接替代/潜在跨界）与评估维度，再列出主要竞品（通常 4–8 家，不足则说明原因）。对比功能能力、定价与包装、获客与渠道、品牌口碑与典型客群，指出差异化机会、应优先跟进的点与应主动避开的红海。输出：竞品短名单、维度对比矩阵、优劣势摘要、机会假设与验证实验建议。引用公开资料与可核验信号（官网、文档、评价、招股/研报若有），标注时间与来源权重。用户若给出我方产品定位或约束，所有建议必须回扣该定位。禁止仅堆砌功能清单；每条机会需说明「对谁、为什么现在、怎么验证」。关注维度默认：功能对比、定价策略、获客渠道、口碑与评价；用户另有维度时覆盖之。结论给出优先级（P0/P1）与不做清单。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。",
    en: "Run a competitor analysis for the user-specified category and produce actionable comparisons. Clarify scope (direct/indirect/adjacent) and evaluation dimensions, list major rivals (typically 4–8; explain if fewer), and compare capabilities, pricing/packaging, GTM/channels, brand sentiment, and typical buyers. Call out differentiation opportunities, what to chase first, and what to avoid. Deliver a shortlist, comparison matrix, strengths/weaknesses, opportunity hypotheses, and validation experiments. Cite public, verifiable signals with dates and source weight. If the user states our positioning or constraints, recommendations must map back to them. Do not dump feature lists—each opportunity must state for whom, why now, and how to test. Default dimensions: features, pricing, GTM, sentiment. Prioritize P0/P1 and include an explicit not-to-do list. Keep the tone crisp and decision-oriented for product and GTM owners.",
  },
  "tech_selection": {
    zh: "请做一轮技术选型调研并给出可落地推荐。先澄清问题陈述、成功标准、硬约束（性能、成本、合规、团队技能、上线窗口）与可选方案清单。对比候选方案在能力边界、性能与成本、生态成熟度、运维复杂度、迁移/锁定风险上的表现，给出推荐路径、备选与迁移注意点。输出：约束表、方案对比表、推荐与理由、风险与回滚、90 天落地里程碑建议。证据来自官方文档、基准测试、生产案例与社区健康度信号，标注版本与日期。若约束冲突，先暴露权衡再给有条件推荐，不要假装存在完美方案。关注维度默认：能力边界、成本与性能、生态成熟度、迁移风险。用户补充业务场景后，用场景贯穿全文示例。语言具体到可执行动作，避免「看情况」「都可以」式空话。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。补充要求：保持结构清晰、可复查、可执行；缺证据先声明缺口；中英专名首次出现可括注。",
    en: "Run a tech-selection study with an actionable recommendation. Clarify the problem, success criteria, hard constraints (performance, cost, compliance, skills, launch window) and candidate options. Compare options on capability fit, cost/performance, ecosystem maturity, ops complexity, and migration/lock-in risk; recommend a path, fallback, and migration notes. Deliver a constraints table, comparison table, recommendation with rationale, risks/rollback, and a 90-day milestone sketch. Evidence from official docs, benchmarks, production cases, and community health—cite versions/dates. If constraints conflict, expose trade-offs before a conditional pick; do not pretend a perfect option exists. Default focus: capability, cost & performance, ecosystem, migration risk. When the user supplies a business scenario, thread it through examples. Prefer concrete next actions over vague hedging.",
  },
} as const;
