#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="${ROOT_DIR}/scripts/publish-release-manifest.sh"

fail() {
  echo "$*" >&2
  exit 1
}

command -v jq >/dev/null 2>&1 || fail "jq is required to run this test"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

archive_dir="$tmp_dir/archives"
mkdir -p "$archive_dir"
for f in \
  multica-cli-0.3.81-linux-amd64.tar.gz \
  multica-cli-0.3.81-linux-arm64.tar.gz \
  multica-cli-0.3.81-darwin-arm64.tar.gz \
  multica_linux_amd64.tar.gz; do
  echo "fake archive $f" >"$archive_dir/$f"
done

checksums="$tmp_dir/checksums.txt"
cat >"$checksums" <<'EOF'
# generated by GoReleaser
aaaa1111  multica-cli-0.3.81-linux-amd64.tar.gz
bbbb2222  multica-cli-0.3.81-linux-arm64.tar.gz
CCCC3333  multica-cli-0.3.81-darwin-arm64.tar.gz
dddd4444  multica_linux_amd64.tar.gz
EOF

out="$(bash "$SCRIPT" v0.3.81 0.3.81 https://cdn.leagent.me/computer/v0.3.81 "$checksums" "$archive_dir")"

echo "$out" | jq -e '.tag == "v0.3.81"' >/dev/null || fail "tag mismatch: $out"
echo "$out" | jq -e '.version == "0.3.81"' >/dev/null || fail "version mismatch: $out"
echo "$out" | jq -e '.platforms["linux-amd64"].sha256 == "aaaa1111"' >/dev/null ||
  fail "linux-amd64 sha256 mismatch: $out"
echo "$out" | jq -e '.platforms["linux-amd64"].url == "https://cdn.leagent.me/computer/v0.3.81/multica-cli-0.3.81-linux-amd64.tar.gz"' >/dev/null ||
  fail "linux-amd64 url mismatch: $out"
echo "$out" | jq -e '.platforms["darwin-arm64"].sha256 == "cccc3333"' >/dev/null ||
  fail "darwin-arm64 sha256 must be lowercased: $out"
echo "$out" | jq -e 'has("platforms") and (.platforms | has("linux-arm64"))' >/dev/null ||
  fail "linux-arm64 missing: $out"
echo "$out" | jq -e '.platforms | length == 3' >/dev/null ||
  fail "legacy multica_linux_amd64.tar.gz entry must not be published as a platform key: $out"

set +e
bash "$SCRIPT" v0.3.81 0.3.81 https://example "$tmp_dir/missing-checksums.txt" "$archive_dir" >"$tmp_dir/out.log" 2>&1
missing_checksums_status=$?
set -e
[[ "$missing_checksums_status" -ne 0 ]] || fail "must fail closed when checksums file is missing"

bad_checksums="$tmp_dir/checksums-missing-archive.txt"
echo "eeee5555  multica-cli-0.3.81-windows-amd64.zip" >"$bad_checksums"
set +e
bash "$SCRIPT" v0.3.81 0.3.81 https://example "$bad_checksums" "$archive_dir" >/dev/null 2>"$tmp_dir/out.log"
missing_archive_status=$?
set -e
[[ "$missing_archive_status" -ne 0 ]] || fail "must fail closed when a checksummed archive file is absent from archive_dir"
grep -Fq "multica-cli-0.3.81-windows-amd64.zip" "$tmp_dir/out.log" ||
  fail "missing-archive error must name the file"

echo "publish-release-manifest ok"
