BEGIN;

-- Migration 210: fence daemon-local Reminder timer projections and fire attempts.
ALTER TABLE agent_reminder
  ADD COLUMN version BIGINT NOT NULL DEFAULT 1
    CHECK (version > 0);

-- Durable replay for Raft-aligned AgentManager start/stop lifecycle. This is
-- a mutation outbox, not a server-derived active-Agent inventory: only an
-- Agent placement transition writes rows. A global event sequence is
-- monotonic for every runtime, while one generated placement generation
-- fences both sides of the same per-Agent move (A-stop/B-start).
CREATE SEQUENCE agent_reminder_placement_generation_seq;

CREATE TABLE agent_reminder_daemon_owner_event (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id UUID NOT NULL,
  workspace_id UUID NOT NULL,
  runtime_id UUID NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('start', 'stop')),
  placement_generation BIGINT NOT NULL CHECK (placement_generation > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX agent_reminder_daemon_owner_event_runtime_idx
  ON agent_reminder_daemon_owner_event (runtime_id, seq);

CREATE INDEX agent_reminder_daemon_owner_event_agent_idx
  ON agent_reminder_daemon_owner_event (agent_id, placement_generation DESC);

CREATE TABLE agent_reminder_daemon_owner_cursor (
  runtime_id UUID PRIMARY KEY,
  ack_seq BIGINT NOT NULL DEFAULT 0 CHECK (ack_seq >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION project_agent_reminder_daemon_owner_event()
RETURNS TRIGGER AS $$
DECLARE
  placement_generation BIGINT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.runtime_id IS NOT NULL AND NEW.archived_at IS NULL THEN
      placement_generation := nextval('agent_reminder_placement_generation_seq');
      INSERT INTO agent_reminder_daemon_owner_event (
        agent_id, workspace_id, runtime_id, event_type, placement_generation
      ) VALUES (NEW.id, NEW.workspace_id, NEW.runtime_id, 'start', placement_generation);
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    IF OLD.runtime_id IS NOT NULL THEN
      placement_generation := nextval('agent_reminder_placement_generation_seq');
      INSERT INTO agent_reminder_daemon_owner_event (
        agent_id, workspace_id, runtime_id, event_type, placement_generation
      ) VALUES (OLD.id, OLD.workspace_id, OLD.runtime_id, 'stop', placement_generation);
    END IF;
    RETURN OLD;
  END IF;

  IF (OLD.runtime_id IS NOT NULL AND (
    OLD.runtime_id IS DISTINCT FROM NEW.runtime_id OR
    (OLD.archived_at IS NULL AND NEW.archived_at IS NOT NULL)
  )) OR (NEW.runtime_id IS NOT NULL AND NEW.archived_at IS NULL AND (
    OLD.runtime_id IS DISTINCT FROM NEW.runtime_id OR
    (OLD.archived_at IS NOT NULL AND NEW.archived_at IS NULL)
  )) THEN
    placement_generation := nextval('agent_reminder_placement_generation_seq');
  END IF;

  IF OLD.runtime_id IS NOT NULL AND (
    OLD.runtime_id IS DISTINCT FROM NEW.runtime_id OR
    (OLD.archived_at IS NULL AND NEW.archived_at IS NOT NULL)
  ) THEN
    INSERT INTO agent_reminder_daemon_owner_event (
      agent_id, workspace_id, runtime_id, event_type, placement_generation
    ) VALUES (OLD.id, OLD.workspace_id, OLD.runtime_id, 'stop', placement_generation);
  END IF;

  IF NEW.runtime_id IS NOT NULL AND NEW.archived_at IS NULL AND (
    OLD.runtime_id IS DISTINCT FROM NEW.runtime_id OR
    (OLD.archived_at IS NOT NULL AND NEW.archived_at IS NULL)
  ) THEN
    INSERT INTO agent_reminder_daemon_owner_event (
      agent_id, workspace_id, runtime_id, event_type, placement_generation
    ) VALUES (NEW.id, NEW.workspace_id, NEW.runtime_id, 'start', placement_generation);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_reminder_daemon_owner_event_trigger
AFTER INSERT OR UPDATE OR DELETE ON agent
FOR EACH ROW EXECUTE FUNCTION project_agent_reminder_daemon_owner_event();

COMMIT;
