BEGIN;

-- Migration 210: fence daemon-local Reminder timer projections and fire attempts.
ALTER TABLE agent_reminder
  ADD COLUMN version BIGINT NOT NULL DEFAULT 1
    CHECK (version > 0);

-- Cutover is fail-closed: every live owner of an active definition must have
-- most recently registered the versioned timer-cache capability. This is a
-- read-only fleet preflight inside the migration transaction; deployment must
-- upgrade/reconnect daemons before retrying migration 210.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM agent_reminder reminder
    JOIN agent ON agent.id = reminder.agent_id
    LEFT JOIN agent_runtime runtime
      ON runtime.id = agent.runtime_id AND runtime.workspace_id = agent.workspace_id
    WHERE reminder.status IN ('scheduled', 'firing')
      AND agent.archived_at IS NULL
      AND (
        runtime.id IS NULL OR
        NOT COALESCE((runtime.metadata->'capabilities') @> '["reminder_versioned_cache_v1"]'::jsonb, false)
      )
  ) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'daemon_outdated';
  END IF;
END;
$$;

-- Calendar recurrence needs the old scheduler's timezone/DST parser to choose
-- its next slot safely. Refuse that rare in-flight cutover state instead of
-- inventing a wall-clock answer in SQL; operators must let the old recovery
-- path settle it before retrying this migration. Fixed intervals are advanced
-- exactly below without producing an immediate duplicate wake.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM agent_reminder reminder
    JOIN agent_reminder_occurrence occurrence
      ON occurrence.id = reminder.current_occurrence_id
    WHERE reminder.status = 'firing'
      AND occurrence.fired_task_id IS NOT NULL
      AND reminder.cadence IS NOT NULL
      AND (
        reminder.cadence_next_at IS NULL OR
        reminder.cadence !~ '^every:[1-9][0-9]*[mhd]$'
      )
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'reminder_cutover_recurring_requires_recovery';
  END IF;
END;
$$;

-- Durable replay for Raft-aligned AgentManager start/stop lifecycle. A global
-- event sequence is monotonic for every runtime, while one generated placement
-- generation fences both sides of the same per-Agent move (A-stop/B-start).
-- Migration also writes exactly one start row for each currently resident
-- Agent so an upgraded daemon and every later timer projection share a real
-- generation from the first cutover connection onward.
CREATE SEQUENCE agent_reminder_placement_generation_seq;

CREATE TABLE agent_reminder_daemon_owner_event (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id UUID NOT NULL,
  workspace_id UUID NOT NULL,
  runtime_id UUID NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('start', 'stop')),
  placement_generation BIGINT NOT NULL CHECK (placement_generation > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX agent_reminder_daemon_owner_event_runtime_idx
  ON agent_reminder_daemon_owner_event (runtime_id, seq);

CREATE INDEX agent_reminder_daemon_owner_event_agent_idx
  ON agent_reminder_daemon_owner_event (agent_id, placement_generation DESC);

CREATE TABLE agent_reminder_daemon_owner_cursor (
  runtime_id UUID PRIMARY KEY,
  ack_seq BIGINT NOT NULL DEFAULT 0 CHECK (ack_seq >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Reminder timer projections share one durable, per-runtime ordered stream.
-- The cursor row keeps the latest sequence even after acknowledged events are
-- garbage-collected, so snapshots always carry a comparable watermark.
CREATE TABLE agent_reminder_daemon_projection_cursor (
  runtime_id UUID PRIMARY KEY REFERENCES agent_runtime(id) ON DELETE CASCADE,
  latest_seq BIGINT NOT NULL DEFAULT 0 CHECK (latest_seq >= 0),
  ack_seq BIGINT NOT NULL DEFAULT 0 CHECK (ack_seq >= 0 AND ack_seq <= latest_seq),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE agent_reminder_daemon_projection_event (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prev_seq BIGINT NOT NULL CHECK (prev_seq >= 0 AND prev_seq < seq),
  runtime_id UUID NOT NULL REFERENCES agent_runtime(id) ON DELETE CASCADE,
  workspace_id UUID NOT NULL,
  agent_id UUID NOT NULL,
  reminder_id UUID NOT NULL,
  placement_generation BIGINT NOT NULL CHECK (placement_generation > 0),
  event_type TEXT NOT NULL CHECK (event_type IN ('upsert', 'cancel', 'fire_result')),
  version BIGINT NOT NULL CHECK (version > 0),
  fire_at TIMESTAMPTZ,
  terminal BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((terminal AND fire_at IS NULL) OR (NOT terminal AND fire_at IS NOT NULL))
);

CREATE INDEX agent_reminder_daemon_projection_event_runtime_idx
  ON agent_reminder_daemon_projection_event (runtime_id, seq);

CREATE INDEX agent_reminder_daemon_projection_event_reminder_idx
  ON agent_reminder_daemon_projection_event (reminder_id, seq DESC);

CREATE OR REPLACE FUNCTION enqueue_agent_reminder_daemon_projection(
  target_runtime_id UUID,
  target_workspace_id UUID,
  target_agent_id UUID,
  target_reminder_id UUID,
  target_placement_generation BIGINT,
  target_event_type TEXT,
  target_version BIGINT,
  target_fire_at TIMESTAMPTZ,
  target_terminal BOOLEAN
) RETURNS BIGINT AS $$
DECLARE
  projected_seq BIGINT;
  previous_seq BIGINT;
BEGIN
  -- Snapshot reads take the same lock before reading definition state and the
  -- latest watermark. This closes the commit-order hole between DB truth and
  -- the outbox sequence allocated for that truth.
  PERFORM pg_advisory_xact_lock(hashtextextended(target_runtime_id::text, 210));

  SELECT COALESCE(latest_seq, 0)
  INTO previous_seq
  FROM agent_reminder_daemon_projection_cursor
  WHERE runtime_id = target_runtime_id;
  previous_seq := COALESCE(previous_seq, 0);

  INSERT INTO agent_reminder_daemon_projection_event (
    prev_seq, runtime_id, workspace_id, agent_id, reminder_id, placement_generation, event_type,
    version, fire_at, terminal
  ) VALUES (
    previous_seq, target_runtime_id, target_workspace_id, target_agent_id,
    target_reminder_id, target_placement_generation, target_event_type, target_version,
    target_fire_at, target_terminal
  ) RETURNING seq INTO projected_seq;

  INSERT INTO agent_reminder_daemon_projection_cursor (runtime_id, latest_seq)
  VALUES (target_runtime_id, projected_seq)
  ON CONFLICT (runtime_id) DO UPDATE
  SET latest_seq = GREATEST(agent_reminder_daemon_projection_cursor.latest_seq, EXCLUDED.latest_seq),
      updated_at = now();
  RETURN projected_seq;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION project_agent_reminder_daemon_timer_event()
RETURNS TRIGGER AS $$
DECLARE
  target_runtime_id UUID;
  target_placement_generation BIGINT;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.version = OLD.version THEN
    RETURN NEW;
  END IF;

  SELECT agent.runtime_id, owner.placement_generation
  INTO target_runtime_id, target_placement_generation
  FROM agent
  JOIN LATERAL (
    SELECT placement_generation
    FROM agent_reminder_daemon_owner_event
    WHERE agent_id = agent.id AND runtime_id = agent.runtime_id
    ORDER BY placement_generation DESC LIMIT 1
  ) owner ON true
  WHERE agent.id = NEW.agent_id
    AND agent.workspace_id = NEW.workspace_id
    AND agent.archived_at IS NULL;

  IF target_runtime_id IS NULL OR target_placement_generation IS NULL THEN
    RETURN NEW;
  END IF;

  IF NEW.status = 'scheduled' THEN
    PERFORM enqueue_agent_reminder_daemon_projection(
      target_runtime_id, NEW.workspace_id, NEW.agent_id, NEW.id,
      target_placement_generation, 'upsert', NEW.version, NEW.fire_at, false
    );
  ELSE
    PERFORM enqueue_agent_reminder_daemon_projection(
      target_runtime_id, NEW.workspace_id, NEW.agent_id, NEW.id,
      target_placement_generation, 'cancel', NEW.version, NULL, true
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_reminder_daemon_timer_event_trigger
AFTER INSERT OR UPDATE ON agent_reminder
FOR EACH ROW EXECUTE FUNCTION project_agent_reminder_daemon_timer_event();

-- A placement with active Reminder definitions may only move to a runtime
-- whose latest registration advertises the cache capability. Registration
-- replaces metadata, so a later downgrade clears this fact automatically.
CREATE OR REPLACE FUNCTION fence_agent_reminder_runtime_capability()
RETURNS TRIGGER AS $$
DECLARE
  target_capable BOOLEAN;
BEGIN
  IF NEW.runtime_id IS NOT DISTINCT FROM OLD.runtime_id THEN
    RETURN NEW;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM agent_reminder
    WHERE agent_id = OLD.id AND status IN ('scheduled', 'firing')
  ) THEN
    RETURN NEW;
  END IF;
  SELECT COALESCE((metadata->'capabilities') @> '["reminder_versioned_cache_v1"]'::jsonb, false)
  INTO target_capable
  FROM agent_runtime
  WHERE id = NEW.runtime_id AND workspace_id = NEW.workspace_id
  FOR SHARE;
  IF NOT COALESCE(target_capable, false) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'daemon_outdated';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_reminder_runtime_capability_trigger
BEFORE UPDATE OF runtime_id ON agent
FOR EACH ROW EXECUTE FUNCTION fence_agent_reminder_runtime_capability();

-- Registration metadata is replaceable, but an active timer placement cannot
-- be downgraded to a daemon that no longer owns the timer capability. Keep the
-- old registration untouched and require the capable daemon to reconnect.
CREATE OR REPLACE FUNCTION fence_agent_runtime_reminder_capability_downgrade()
RETURNS TRIGGER AS $$
BEGIN
  IF COALESCE((OLD.metadata->'capabilities') @> '["reminder_versioned_cache_v1"]'::jsonb, false)
     AND NOT COALESCE((NEW.metadata->'capabilities') @> '["reminder_versioned_cache_v1"]'::jsonb, false)
     AND EXISTS (
       SELECT 1
       FROM agent_reminder reminder
       JOIN agent ON agent.id = reminder.agent_id
       WHERE agent.runtime_id = OLD.id
         AND agent.archived_at IS NULL
         AND reminder.status IN ('scheduled', 'firing')
     )
  THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'daemon_outdated';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_runtime_reminder_capability_downgrade_trigger
BEFORE UPDATE OF metadata ON agent_runtime
FOR EACH ROW EXECUTE FUNCTION fence_agent_runtime_reminder_capability_downgrade();

CREATE OR REPLACE FUNCTION project_agent_reminder_daemon_owner_event()
RETURNS TRIGGER AS $$
DECLARE
  placement_generation BIGINT;
  reminder_row RECORD;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.runtime_id IS NOT NULL AND NEW.archived_at IS NULL THEN
      placement_generation := nextval('agent_reminder_placement_generation_seq');
      INSERT INTO agent_reminder_daemon_owner_event (
        agent_id, workspace_id, runtime_id, event_type, placement_generation
      ) VALUES (NEW.id, NEW.workspace_id, NEW.runtime_id, 'start', placement_generation);
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    IF OLD.runtime_id IS NOT NULL THEN
      placement_generation := nextval('agent_reminder_placement_generation_seq');
      INSERT INTO agent_reminder_daemon_owner_event (
        agent_id, workspace_id, runtime_id, event_type, placement_generation
      ) VALUES (OLD.id, OLD.workspace_id, OLD.runtime_id, 'stop', placement_generation);

      FOR reminder_row IN
        UPDATE agent_reminder
        SET status = 'cancelled', terminal_reason = 'agent_deleted',
            current_occurrence_id = NULL, version = version + 1, updated_at = now()
        WHERE agent_id = OLD.id AND status IN ('scheduled', 'firing')
        RETURNING *
      LOOP
        INSERT INTO agent_reminder_lifecycle_event (
          reminder_id, workspace_id, agent_id, event_type, actor_type,
          previous_fire_at, title_snapshot, cadence_snapshot, timezone_snapshot,
          resulting_state, reason_code
        ) VALUES (
          reminder_row.id, reminder_row.workspace_id, reminder_row.agent_id,
          'cancelled', 'system', reminder_row.fire_at, reminder_row.title,
          reminder_row.cadence, reminder_row.schedule_timezone,
          'cancelled', 'agent_deleted'
        );
        PERFORM enqueue_agent_reminder_daemon_projection(
          OLD.runtime_id, reminder_row.workspace_id, reminder_row.agent_id,
          reminder_row.id, placement_generation, 'cancel', reminder_row.version, NULL, true
        );
      END LOOP;
    END IF;
    RETURN OLD;
  END IF;

  IF (OLD.runtime_id IS NOT NULL AND (
    OLD.runtime_id IS DISTINCT FROM NEW.runtime_id OR
    (OLD.archived_at IS NULL AND NEW.archived_at IS NOT NULL)
  )) OR (NEW.runtime_id IS NOT NULL AND NEW.archived_at IS NULL AND (
    OLD.runtime_id IS DISTINCT FROM NEW.runtime_id OR
    (OLD.archived_at IS NOT NULL AND NEW.archived_at IS NULL)
  )) THEN
    placement_generation := nextval('agent_reminder_placement_generation_seq');
  END IF;

  IF OLD.runtime_id IS NOT NULL AND (
    OLD.runtime_id IS DISTINCT FROM NEW.runtime_id OR
    (OLD.archived_at IS NULL AND NEW.archived_at IS NOT NULL)
  ) THEN
    INSERT INTO agent_reminder_daemon_owner_event (
      agent_id, workspace_id, runtime_id, event_type, placement_generation
    ) VALUES (OLD.id, OLD.workspace_id, OLD.runtime_id, 'stop', placement_generation);

    IF OLD.archived_at IS NULL AND NEW.archived_at IS NOT NULL THEN
      FOR reminder_row IN
        UPDATE agent_reminder
        SET status = 'cancelled', terminal_reason = 'agent_archived',
            current_occurrence_id = NULL, version = version + 1, updated_at = now()
        WHERE agent_id = OLD.id AND status IN ('scheduled', 'firing')
        RETURNING *
      LOOP
        INSERT INTO agent_reminder_lifecycle_event (
          reminder_id, workspace_id, agent_id, event_type, actor_type,
          previous_fire_at, title_snapshot, cadence_snapshot, timezone_snapshot,
          resulting_state, reason_code
        ) VALUES (
          reminder_row.id, reminder_row.workspace_id, reminder_row.agent_id,
          'cancelled', 'system', reminder_row.fire_at, reminder_row.title,
          reminder_row.cadence, reminder_row.schedule_timezone,
          'cancelled', 'agent_archived'
        );
        PERFORM enqueue_agent_reminder_daemon_projection(
          OLD.runtime_id, reminder_row.workspace_id, reminder_row.agent_id,
          reminder_row.id, placement_generation, 'cancel', reminder_row.version, NULL, true
        );
      END LOOP;
    END IF;
  END IF;

  IF NEW.runtime_id IS NOT NULL AND NEW.archived_at IS NULL AND (
    OLD.runtime_id IS DISTINCT FROM NEW.runtime_id OR
    (OLD.archived_at IS NOT NULL AND NEW.archived_at IS NULL)
  ) THEN
    INSERT INTO agent_reminder_daemon_owner_event (
      agent_id, workspace_id, runtime_id, event_type, placement_generation
    ) VALUES (NEW.id, NEW.workspace_id, NEW.runtime_id, 'start', placement_generation);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_reminder_daemon_owner_event_trigger
AFTER INSERT OR UPDATE OR DELETE ON agent
FOR EACH ROW EXECUTE FUNCTION project_agent_reminder_daemon_owner_event();

-- Establish the cutover generation for Agents that were already resident
-- before the lifecycle trigger existed. The daemon replays these rows before
-- projection replay and snapshots, so stale pre-move events cannot arm a timer
-- during reconnect.
INSERT INTO agent_reminder_daemon_owner_event (
  agent_id, workspace_id, runtime_id, event_type, placement_generation
)
SELECT id, workspace_id, runtime_id, 'start', nextval('agent_reminder_placement_generation_seq')
FROM agent
WHERE runtime_id IS NOT NULL AND archived_at IS NULL;

-- Converge V2 rows that were left in the removed server scheduler's firing
-- state. A durable task means delivery already happened: finish the ledger and
-- never enqueue another wake. Without a task, cancel the partial occurrence
-- and re-arm the definition at a new version. Partial receipts are preserved
-- as audit evidence but cannot collide with the new occurrence slot.
CREATE OR REPLACE FUNCTION agent_reminder_cutover_next_every(
  cadence_rule TEXT,
  cadence_slot TIMESTAMPTZ,
  reference_time TIMESTAMPTZ
) RETURNS TIMESTAMPTZ AS $$
DECLARE
  cadence_parts TEXT[];
  cadence_count BIGINT;
  cadence_step INTERVAL;
  candidate TIMESTAMPTZ;
  missed BIGINT;
BEGIN
  cadence_parts := regexp_match(cadence_rule, '^every:([1-9][0-9]*)([mhd])$');
  IF cadence_parts IS NULL OR cadence_slot IS NULL THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'reminder_cutover_recurring_requires_recovery';
  END IF;
  cadence_count := cadence_parts[1]::BIGINT;
  cadence_step := cadence_count * CASE cadence_parts[2]
    WHEN 'm' THEN INTERVAL '1 minute'
    WHEN 'h' THEN INTERVAL '1 hour'
    WHEN 'd' THEN INTERVAL '1 day'
  END;
  candidate := cadence_slot + cadence_step;
  IF candidate > reference_time THEN
    RETURN candidate;
  END IF;
  missed := floor(
    extract(epoch FROM (reference_time - candidate)) /
    extract(epoch FROM cadence_step)
  )::BIGINT + 1;
  RETURN candidate + missed * cadence_step;
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;

WITH delivered AS (
  UPDATE agent_reminder_occurrence occurrence
  SET status = 'fired', fired_at = COALESCE(occurrence.fired_at, now()), updated_at = now()
  FROM agent_reminder reminder
  WHERE reminder.status = 'firing'
    AND reminder.current_occurrence_id = occurrence.id
    AND occurrence.fired_task_id IS NOT NULL
  RETURNING reminder.id, reminder.cadence, occurrence.fired_task_id
)
UPDATE agent_reminder reminder
SET status = CASE WHEN delivered.cadence IS NULL THEN 'fired' ELSE 'scheduled' END,
    fire_at = CASE
      WHEN delivered.cadence IS NULL THEN reminder.fire_at
      ELSE agent_reminder_cutover_next_every(reminder.cadence, reminder.cadence_next_at, transaction_timestamp())
    END,
    cadence_next_at = CASE
      WHEN delivered.cadence IS NULL THEN reminder.cadence_next_at
      ELSE agent_reminder_cutover_next_every(reminder.cadence, reminder.cadence_next_at, transaction_timestamp())
    END,
    fired_task_id = delivered.fired_task_id,
    fired_at = COALESCE(reminder.fired_at, now()),
    current_occurrence_id = NULL,
    version = reminder.version + 1,
    updated_at = now()
FROM delivered
WHERE reminder.id = delivered.id;

DROP FUNCTION agent_reminder_cutover_next_every(TEXT, TIMESTAMPTZ, TIMESTAMPTZ);

WITH retryable AS (
  UPDATE agent_reminder_occurrence occurrence
  SET status = 'cancelled', terminal_reason = 'daemon_cutover_rearm', updated_at = now()
  FROM agent_reminder reminder
  WHERE reminder.status = 'firing'
    AND reminder.current_occurrence_id = occurrence.id
    AND occurrence.fired_task_id IS NULL
  RETURNING reminder.id, occurrence.receipt_message_id
)
UPDATE agent_reminder reminder
SET status = 'scheduled',
    fire_at = CASE WHEN retryable.receipt_message_id IS NULL THEN reminder.fire_at ELSE now() END,
    cadence_next_at = CASE
      WHEN reminder.cadence IS NULL THEN NULL
      WHEN retryable.receipt_message_id IS NULL THEN reminder.cadence_next_at
      ELSE now()
    END,
    current_occurrence_id = NULL,
    version = reminder.version + 1,
    updated_at = now()
FROM retryable
WHERE reminder.id = retryable.id;

COMMIT;
